name: Eleventy Build
on: [push]

# Conditional environmental if's      
env:
  UPDATE_NPM: true # false = deploy eleventy , true = update npm

jobs:
  build_deploy_eleventy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm i # npm i # npm update --save
        
      - name: Npm Build
        if: env.UPDATE_NPM != 'true'
        run: npm run build
        
      - name: Deploy
        if: env.UPDATE_NPM != 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
          
      - name: pull request on npm update
        if: env.UPDATE_NPM == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update dependencies
          title: Update dependencies
          body: |
            - Dependency updates
  
            Auto-generated by [create-pull-request][1]
  
            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-dependencies
